datasource.url=jdbc:mysql://localhost:3306/Dende_Eventos_Marselha?useSSL=false&serverTimezone=UTC
datasource.username=root
datasource.password=81733967
datasource.driver-class-name=com.mysql.cj.jdbc.Driver
datasource.hikari.maximum-pool-size=10
datasource.hikari.minimum-idle=2
datasource.hikari.connection-timeout=30000